# These are supported funding model platforms

github: [2searx2cool]
patreon: 2searx2cool
open_collective: 2searx2cool
ko_fi: 2searx2cool
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://2searx2cool.com/donate']